TrainingCentersCRM/TrainingCentersCRM/Controllers/VacancyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
<<<<<<< HEAD

namespace TrainingCentersCRM.Models
{
    public class VacancyController : Controller
=======
using TrainingCentersCRM.Infrastructure;
using TrainingCentersCRM.Models;
using TrainingCentersCRM.Models.ViewModels;

namespace TrainingCentersCRM.Controllers
{
    public class VacancyController : RoutingTrainingCenterController
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    {
        private TrainingCentersDBEntities db = new TrainingCentersDBEntities();

        // GET: /Vacancy/
        public ActionResult Index()
        {
<<<<<<< HEAD
            return View(db.Vacancies.ToList());
=======
            var res = db.Vacancies.Where(a => a.IdTrainingCenter == trainingCenter.Id 
                || a.IdTrainingCenter == db.TrainingCenters.FirstOrDefault(b => b.Url == "empty").Id 
                || a.IdTrainingCenter == null);
            return View(res);
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
        }

        // GET: /Vacancy/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
<<<<<<< HEAD
            Vacancy vacancy = db.Vacancies.Find(id);
=======
            Vacancy vacancy = db.Vacancies.Where(c => c.Id == id).Include(c => c.Qualifications).Single();
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
            if (vacancy == null)
            {
                return HttpNotFound();
            }
            return View(vacancy);
        }

        // GET: /Vacancy/Create
<<<<<<< HEAD
        public ActionResult Create()
        {
=======
        [TCAuthorize(Roles = "admin")]
        public ActionResult Create()
        {
            var vacancy = new Vacancy();
            vacancy.Qualifications = new List<Qualification>();
            PopulateRelatedTagData(vacancy);
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
            return View();
        }

        // POST: /Vacancy/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
<<<<<<< HEAD
        public ActionResult Create([Bind(Include="Id,Description,Organization,Wages,Additionally,Link")] Vacancy vacancy)
        {
=======
        [TCAuthorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "Id,IdTrainingCenter,Description,Organization,Wages,Additionally,Link")] Vacancy vacancy, string[] selectedQualifications)
        {
            if (selectedQualifications != null)
            {
                vacancy.Qualifications = new List<Qualification>();
                foreach (var qualification in selectedQualifications)
                {
                    var qualificationToAdd = db.Qualifications.Find(int.Parse(qualification));
                    vacancy.Qualifications.Add(qualificationToAdd);
                }
            }
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
            if (ModelState.IsValid)
            {
                db.Vacancies.Add(vacancy);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
<<<<<<< HEAD

            return View(vacancy);
        }

        // GET: /Vacancy/Edit/5
=======
            PopulateRelatedTagData(vacancy);
            return View(vacancy);
        }

        private void PopulateRelatedTagData(Vacancy vacancy)
        {
            var allQualifications = db.Qualifications;
            var instructionTags = new HashSet<int>(vacancy.Qualifications.Select(c => c.Id));
            var viewModel = new List<RelatedQualifications>();
            foreach (var qualification in allQualifications)
            {
                viewModel.Add(new RelatedQualifications
                {
                    QualificationID = qualification.Id,
                    Title = qualification.Title,
                    Assigned = instructionTags.Contains(qualification.Id)
                });
            }
            ViewBag.Qualifications = viewModel;
        }

        // GET: /Vacancy/Edit/5
        [TCAuthorize(Roles = "admin")]
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy vacancy = db.Vacancies.Find(id);
            if (vacancy == null)
            {
                return HttpNotFound();
            }
<<<<<<< HEAD
=======
            PopulateRelatedTagData(vacancy);
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
            return View(vacancy);
        }

        // POST: /Vacancy/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
<<<<<<< HEAD
        public ActionResult Edit([Bind(Include="Id,Description,Organization,Wages,Additionally,Link")] Vacancy vacancy)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vacancy).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vacancy);
        }

        // GET: /Vacancy/Delete/5
=======
        [TCAuthorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,Description,Organization,Wages,Additionally,Link")] Vacancy vacancy, string[] selectedQualifications)
        {
            var vacancyToupdate = db.Vacancies.Where(i => i.Id == vacancy.Id).Include(i => i.Qualifications).Single();
            if (ModelState.IsValid)
            {
                UpdateInstructionTags(selectedQualifications, vacancyToupdate);
                db.Entry(vacancyToupdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(vacancyToupdate);
        }

        private void UpdateInstructionTags(string[] selectedQualifications, Vacancy vacancyToUpdate)
        {
            if (selectedQualifications == null)
            {
                vacancyToUpdate.Qualifications = new List<Qualification>();
                return;
            }

            var selectedQualificationsHS = new HashSet<string>(selectedQualifications);
            var VacancyQualifications = new HashSet<int>
                (vacancyToUpdate.Qualifications.Select(c => c.Id));
            foreach (var qualification in db.Qualifications)
            {
                if (selectedQualificationsHS.Contains(qualification.Id.ToString()))
                {
                    if (!VacancyQualifications.Contains(qualification.Id))
                    {
                        vacancyToUpdate.Qualifications.Add(qualification);
                    }
                }
                else
                {
                    if (VacancyQualifications.Contains(qualification.Id))
                    {
                        vacancyToUpdate.Qualifications.Remove(qualification);
                    }
                }
            }
        }

        // GET: /Vacancy/Delete/5
        [TCAuthorize(Roles = "admin")]
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy vacancy = db.Vacancies.Find(id);
            if (vacancy == null)
            {
                return HttpNotFound();
            }
            return View(vacancy);
        }

        // POST: /Vacancy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
<<<<<<< HEAD
=======
        [TCAuthorize(Roles = "admin")]
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
        public ActionResult DeleteConfirmed(int id)
        {
            Vacancy vacancy = db.Vacancies.Find(id);
            db.Vacancies.Remove(vacancy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingCentersCRM/TrainingCentersCRM/Views/Vacancy/Create.cshtml
@model TrainingCentersCRM.Models.Vacancy

@{
    ViewBag.Title = "Create";
}
<<<<<<< HEAD

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vacancy</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Organization, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Organization)
                @Html.ValidationMessageFor(model => model.Organization)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Wages, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Wages)
                @Html.ValidationMessageFor(model => model.Wages)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Additionally, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Additionally)
                @Html.ValidationMessageFor(model => model.Additionally)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link)
                @Html.ValidationMessageFor(model => model.Link)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
=======
<div class="container">
    <h2>Создать</h2>


    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Вакансия</h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Organization, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Organization)
                    @Html.ValidationMessageFor(model => model.Organization)
                </div>
            </div>
            <input type="hidden" name="IdTrainingCenter" value="@TCHelper.GetCurrentTc().Id" />

            <div class="form-group">
                @Html.LabelFor(model => model.Wages, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Wages)
                    @Html.ValidationMessageFor(model => model.Wages)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Additionally, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Additionally)
                    @Html.ValidationMessageFor(model => model.Additionally)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Link, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Link)
                    @Html.ValidationMessageFor(model => model.Link)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10" style="display: none">
                    <table>
                        <tr>
                            @{
                                int cnt = 0;
                                List<TrainingCentersCRM.Models.ViewModels.RelatedQualifications> qualifications = ViewBag.Qualifications;
                                if (qualifications != null)
                                {
                                    foreach (var qualification in qualifications)
                                    {
                                        if (cnt++ % 3 == 0)
                                        {
                                            @:</tr><tr>
                                        }
                                            @:<td hidden="true">
                                                <input type="checkbox"
                                                       name="selectedQualifications"
                                                       value="@qualification.QualificationID"
                                                       @(Html.Raw(qualification.Assigned ? "checked=\"checked\"" : "")) />
                                                @:  @qualification.Title
                                              @:</td>
                                    }
                                }
                                @:</tr>
                            }
                        </table>
                    </div>
                    <label>Квалификации</label>
                    <div class="row">
                        <div id="qualificationTree" style="width: 400px; margin-top:20px; overflow-x: scroll; white-space: nowrap; float: left"></div>
                    </div>
                </div>


            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    }
</div>
@section Scripts {
    <script src="~/Scripts/vacancyTree.js"></script>
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878
    @Scripts.Render("~/bundles/jqueryval")
}

TrainingCentersCRM/TrainingCentersCRM/Views/Vacancy/Delete.cshtml
@model TrainingCentersCRM.Models.Vacancy

@{
    ViewBag.Title = "Delete";
}
<<<<<<< HEAD

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vacancy</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organization)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Additionally)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Additionally)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
=======
<div class="container">
    <h2>Удалить</h2>

    <h3>Вы действительно хотите удалить эту вакансию?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Organization)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Organization)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Wages)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Wages)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Additionally)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Additionally)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Link)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Link)
            </dd>

        </dl>

        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Удалить" class="btn btn-default" /> |
                @Html.ActionLink("вернуться к списку вакансий", "Index")
            </div>
        }
    </div>
</div>
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878

TrainingCentersCRM/TrainingCentersCRM/Views/Vacancy/Details.cshtml
@model TrainingCentersCRM.Models.Vacancy

@{
    ViewBag.Title = "Details";
}
<<<<<<< HEAD

<h2>Details</h2>

<div>
    <h4>Vacancy</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organization)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organization)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Wages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Wages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Additionally)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Additionally)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Link)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
=======
<div class="container">
    <h2>Вакансии</h2>


    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Organization)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Organization)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Wages)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Wages)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Additionally)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Additionally)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Link)
            </dt>

            <dd></dd>

            <dt>
                @Html.Label("Требуемые квалификации")
            </dt>

            <dd>
                @if (Model.Qualifications != null)
                {
                    foreach (var qualification in Model.Qualifications)
                    {
                        @Html.Raw(qualification.Title + " ")
                    }
                }

            </dd>
            <dd>
                @Html.DisplayFor(model => model.Link)
            </dd>

        </dl>
    </div>
    <p>
        @if (RolesHelper.IsUserHasPermissionForTc("admin"))
        {
            @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id })
            <span>|</span>
        }
        @Html.ActionLink("Вернуться к списку вакансий", "Index")
    </p>
</div>
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878

TrainingCentersCRM/TrainingCentersCRM/Views/Vacancy/Index.cshtml
@model IEnumerable<TrainingCentersCRM.Models.Vacancy>
<<<<<<< HEAD

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Organization)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Wages)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Additionally)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Link)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Organization)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Wages)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Additionally)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Link)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
=======
@using TrainingCentersCRM.Infrastructure;

@{
    ViewBag.Title = "Вакансии";
}

<script>
    var tcHHId = '@TCHelper.GetCurrentTc().HHCityId';
    var url = '';
    if (tcHHId == '' || tcHHId == 'empty')
        url = "https://api.hh.ru/vacancies?specialization=1&salary=30000&only_with_salary=true";
    else
        url = "https://api.hh.ru/vacancies?specialization=1&salary=30000&only_with_salary=true&area=" + tcHHId;
    $.getJSON(url).done(function (msg) {
        var items = msg.items;
        var promise = new Promise(function (resolve, reject) {
            var complete = 0;
            for (var i = 0; i < items.length; i++) {
                $.getJSON("https://api.hh.ru/vacancies/" + items[i].id).done(function (item) {
                    var content = "";
                    var tmpl = $("#template");
                    tmpl.find("h5.title").text(item.name)
                    tmpl.find(".description").html(item.description)
                    tmpl.find(".salary").text(item.salary.from)
                    tmpl.find(".city").text(item.area.name)
                    tmpl.find(".company").text(item.employer.name)
                    tmpl.find(".link").attr("href", item.alternate_url)
                    content += tmpl.html();
                    $("#jobs").append(content);
                    complete++;
                    if (complete == items.length) {
                        resolve();
                    }
                });

            }
        });
        promise.then(function (result) {
            $('.show-more').click(function (e) {
                e.preventDefault();
                var moreText = $(this).parent().find('.more-hide');
                if (moreText.hasClass('hide')) {
                    moreText.removeClass('hide');
                    $(this).html('Скрыть');
                }
                else {
                    moreText.addClass('hide');
                    $(this).html('Показать подробнее')
                }
            });
        });
    });


</script>
<div class="container row">
    @if (RolesHelper.IsUserHasPermissionForTc("admin"))
    {
        <a>
            @Html.ActionLink("Добавить вакансию", "Create", null, new { @class = "button" })
        </a>
    }
    @if (Model != null && Model.Count() > 0)
    {
        <h3>Вакансии учебного центра</h3>
        <ul class="small-block-grid-2">

            @foreach (var item in Model)
            {
                <li>
                    <div class="card shadow ">
                        <div class="card-section">
                            <h4>
                                <a href="@Url.Action("Details", "Vacancy", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Description)</a>
                                @if (RolesHelper.IsUserHasPermissionForTc("admin"))
                                {
                                    @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "fa fa-pencil", @title = "Редактировать" })
                                    @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "fa fa-trash-o", @title = "Удалить" })
                                }
                            </h4>
                            <b>
                                @Html.DisplayFor(modelItem => item.Organization)
                            </b>
                            <br />
                            <p>
                                <b>Заработная плата:</b> @Html.DisplayFor(modelItem => item.Wages)
                            </p>
                        </div>
                    </div>
                </li>
            }
        </ul>

    }
    <hr />
    <h3>Вакансии HeadHunter</h3>
    <div id="jobs"></div>
    <div id="template" style="display: none;">
        <div class="column small-6 job">
            <h5 class="title"> My job </h5>
            <div>
                <span class="ligth-text"> Компания: </span> <span class="company">Dsf</span>
            </div>
            <div class="salary-wrap"><span class="ligth-text"> Заработная плата: </span> от <span class="salary">1000000</span> </div>
            <div><span class="ligth-text"> Город: </span> <span class="city">Ekmdzf</span> </div>
            <div class="more-hide hide">
                <p class="ligth-text">Описание:</p>
                <div class="description">sdfsdfsdfvvgrvvd</div>
            </div>
            <a class="show-more">Подробнее</a> |
            <a href="#" class="link" target="_blank"> Открыть на HH </a>
            <hr />
            <br />
        </div>
    </div>
</div>
>>>>>>> 77e7434ea7678d938336fcb397236ab4ac0ef878