TrainingCentersCRM/TrainingCentersCRM/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingCentersCRM.Models;

namespace TrainingCentersCRM.Controllers
{
    public class TeacherController : RoutingTrainingCenterController
    {
        private TrainingCentersDBEntities db = new TrainingCentersDBEntities();

        // GET: /Teacher/
        public ActionResult Index()
        {
            return View(db.Teachers.ToList());
        }

        // GET: /Teacher/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // GET: /Teacher/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Teacher/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,LastName,FirstName,Patronymic,Email,Description,Phone")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(teacher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(teacher);
        }

        // GET: /Teacher/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: /Teacher/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,LastName,FirstName,Patronymic,Email,Description,Phone")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teacher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teacher);
        }

        // GET: /Teacher/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: /Teacher/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Teacher teacher = db.Teachers.Find(id);
            db.Users.Remove(teacher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingCentersCRM/TrainingCentersCRM/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingCentersCRM.Infrastructure;
using TrainingCentersCRM.Models;

namespace TrainingCentersCRM.Controllers
{
    public class TeachersController : RoutingTrainingCenterController
    {
        private TrainingCentersDBEntities db = new TrainingCentersDBEntities();

        // GET: /Teacher/
        public ActionResult Index()
        {
            var teacher = db.Teachers.ToList();
            var tcUrl = RouteData.Values["tc"];
            var tc = db.TrainingCenters.SingleOrDefault(a => a.Url == tcUrl);
            var trainingCenterTeachers = db.TrainingCenterTeachers.Where(a => a.IdTrainingCenter == tc.Id).Select(b => b.Teacher);
            return View(trainingCenterTeachers);
        }

        // GET: /Teacher/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // GET: /Teacher/Create
        [TCAuthorize(Roles = "admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Teacher/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [TCAuthorize(Roles = "admin")]
        public ActionResult Create([Bind(Include = "Id,LastName,FirstName,Patronymic,Email,Description,Phone")] Teacher teacher, HttpPostedFileBase uploadImage)
        {
            var tcUrl = RouteData.Values["tc"];
            var tc = db.TrainingCenters.SingleOrDefault(a => a.Url == tcUrl);

            if (ModelState.IsValid)
            {
                if (uploadImage != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                    // установка массива байтов
                    teacher.Image = imageData;
                }
                db.Users.Add(teacher);
                db.SaveChanges();
                var teach = db.Teachers.FirstOrDefault(a => a.Email == teacher.Email);
                TrainingCenterTeacher trainingCenterTeacher = new TrainingCenterTeacher() { IdTeacher = teach.Id, IdTrainingCenter = tc.Id };
                db.TrainingCenterTeachers.Add(trainingCenterTeacher);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(teacher);
        }

        [OutputCache(Duration=3000, VaryByParam="id")]
        public ActionResult Image(int id)
        {
            byte[] imageData = db.Teachers.SingleOrDefault(a => a.Id == id).Image;
            if (imageData == null)
                return null;
            return File(imageData, "image/jpeg");
        }

        // GET: /Teacher/Edit/5
        [TCAuthorize(Roles = "admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: /Teacher/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [TCAuthorize(Roles = "admin")]
        public ActionResult Edit([Bind(Include = "Id,LastName,FirstName,Patronymic,Email,Description,Phone")] Teacher teacher, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                var old =  db.Teachers.Single(a => a.Id == teacher.Id);
                if (uploadImage != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                    // установка массива байтов
                    old.Image = imageData;
                }
                old.Description = teacher.Description;
                old.Email = teacher.Email;
                old.FirstName = teacher.FirstName;
                old.LastName = teacher.LastName;
                old.Patronymic = teacher.Patronymic;
                old.Phone = teacher.Phone;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(teacher);
        }

        // GET: /Teacher/Delete/5
        [TCAuthorize(Roles = "admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Teacher teacher = db.Teachers.Find(id);
            if (teacher == null)
            {
                return HttpNotFound();
            }
            return View(teacher);
        }

        // POST: /Teacher/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [TCAuthorize(Roles = "admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Teacher teacher = db.Teachers.Find(id);
            db.Users.Remove(teacher);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TrainingCentersCRM/TrainingCentersCRM/Views/Teachers/Create.cshtml
@model TrainingCentersCRM.Models.Teacher

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <h2>Создание данных о преподавателе</h2>


    @using (Html.BeginForm("Create", "Teachers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName)
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName)
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Patronymic, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Patronymic)
                    @Html.ValidationMessageFor(model => model.Patronymic)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone)
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>
            </div>
            <div class="editor-label">Файл изображения</div>
            <div class="editor-field">
                <input type="file" name="uploadImage" />
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Добавить" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <br />
    <div>
        @Html.ActionLink("Вернуться", "Index")
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TrainingCentersCRM/TrainingCentersCRM/Views/Teachers/Delete.cshtml
@model TrainingCentersCRM.Models.Teacher

@{
    ViewBag.Title = "Удаление данных о преподавателе";
}
<div class="row">

    <h2>Удаление данных о преподавателе</h2>

    <h3>
        Вы действительно хотите удалить данные о преподавателе &nbsp;@Html.DisplayFor(model => model.LastName) &nbsp;@Html.DisplayFor(model => model.FirstName)&nbsp;@Html.DisplayFor(model => model.Patronymic)?</h3>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> 
            <br /><br />
            @Html.ActionLink("Вернуться", "Index")
        </div>
    }
</div>

TrainingCentersCRM/TrainingCentersCRM/Views/Teachers/Details.cshtml
@model TrainingCentersCRM.Models.Teacher
@{
    ViewBag.Title = "Информация о преподавателе";
}
<div class="container row">
    <h4>Преподаватель учебного центра</h4>
    <p>
        @if (RolesHelper.IsUserHasPermissionForTc("admin"))
        {
            @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id })
        }
    </p>
    <br />
    <div class="row">
        
        <div class="column small-3">
            <img src="/empty/Teachers/Image/@Model.Id" />
        </div>
        <div class="column small-9 left">
            <h3>
                @Html.DisplayFor(model => model.FirstName)
                @Html.DisplayFor(model => model.Patronymic)
                @Html.DisplayFor(model => model.LastName)
            </h3>
            <br />
            <b>@Html.DisplayNameFor(model => model.Email): </b>
            @Html.DisplayFor(model => model.Email)
            <br />
            <b>@Html.DisplayNameFor(model => model.Phone): </b>
            @Html.DisplayFor(model => model.Phone)
            <br /><br />
            <p class="description">
                @Html.DisplayFor(model => model.Description)
            </p>
        </div>
    </div>
</div>

TrainingCentersCRM/TrainingCentersCRM/Views/Teachers/Edit.cshtml
@model TrainingCentersCRM.Models.Teacher

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <h2>Редактирование данных о преподавателе</h2>


    @using (Html.BeginForm("Edit", "Teachers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName)
                    @Html.ValidationMessageFor(model => model.LastName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName)
                    @Html.ValidationMessageFor(model => model.FirstName)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Patronymic, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Patronymic)
                    @Html.ValidationMessageFor(model => model.Patronymic)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email)
                    @Html.ValidationMessageFor(model => model.Email)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description)
                    @Html.ValidationMessageFor(model => model.Description)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Phone)
                    @Html.ValidationMessageFor(model => model.Phone)
                </div>
            </div>
            <br />

            <img src="/empty/Teachers/Image/@Model.Id" class="detailsImage" />

            <div class="editor-label">Файл изображения</div>
            <div class="editor-field">
                <input type="file" name="uploadImage" />
            </div>

            <br />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
</div>

TrainingCentersCRM/TrainingCentersCRM/Views/Teachers/Index.cshtml
@model IEnumerable<TrainingCentersCRM.Models.Teacher>

@{
    ViewBag.Title = "Преподаватели";
}
<link rel="stylesheet" href="/Content/module.css">
<div class="container row">
    <h2>Преподаватели учебного центра</h2>
        @if (RolesHelper.IsUserHasPermissionForTc("admin"))
        {
            @Html.ActionLink("Добавить", "Create", null, new { @class = "button left" })
        }
    <section class="row teachers-blocks">
        <ul class="small-block-grid-1 medium-block-grid-2 large-block-grid-4">
            @foreach (TrainingCentersCRM.Models.Teacher t in Model)
            {
                <li>
                    <div class="shadow">
                        <div class="tools">
                            @if (RolesHelper.IsUserHasPermissionForTc("admin"))
                            {
                                @Html.ActionLink(" ", "Edit", new { id = t.Id }, new { @class = "button fa fa-pencil", @title = "Редактировать" })
                                @Html.ActionLink(" ", "Details", new { id = t.Id }, new { @class = "button fa fa-chevron-circle-down", @title = "Подробнее" })
                                @Html.ActionLink(" ", "Delete", new { id = t.Id }, new { @class = "button fa fa-trash-o", @title = "Удалить" })
                            }
                        </div>
                        <a class="more-info" href="/@TCHelper.GetCurrentTCName()/Teachers/Details/@t.Id" target="_self">
                            <div class="scale-wrap">
                                @if (t.Image != null)
                                {
                                    @Html.Raw("<img class='scale-img' src='/empty/Teachers/Image/" + t.Id + "'/>")
                                }
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name"><b>@t.FirstName @t.Patronymic <br />@t.LastName </b></p>
                                <p class="teacher-description">
                                    @(t.Description != null && t.Description.Length > 190 ? t.Description.Substring(0, 190) + "..." : t.Description)
                                </p>
                            </div>
                        </a>
                    </div>
                </li>
            }
        </ul>
    </section>
</div>