TrainingCentersCRM/TrainingCentersCRM/Models/ViewModels/UserRolesViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace TrainingCentersCRM.Models
{
    public class SelectionRoleEditorViewModel
    {
        public string Name { get; set; }
        public bool Selected { get; set; }
    }

    public class SelectionUserEditorViewModel
    {
        public string UserName { get; set; }
        public string Id { get; set; }
        public List<SelectionRoleEditorViewModel> Roles { get; set; }

        public SelectionUserEditorViewModel()
        {
            this.Roles = new List<SelectionRoleEditorViewModel>();
        }
    }

    public class SelectionUsersRolesViewModel
    {
        public List<SelectionUserEditorViewModel> Users { get; set; }

        public SelectionUsersRolesViewModel()
        {
            this.Users = new List<SelectionUserEditorViewModel>();
        }
    }
}

TrainingCentersCRM/TrainingCentersCRM/Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrainingCentersCRM.Models;
using TrainingCentersCRM.Controllers;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Threading.Tasks;

namespace TrainingCentersCRM.Controllers.Admin
{
    [Authorize(Roles = "admin")]
    public class UserRolesController : Controller
    {

        ApplicationDbContext context = new ApplicationDbContext();
        //
        // GET: /Roles?tc=ulstu
        public ActionResult Index(string tc = "")
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

            var model = new SelectionUsersRolesViewModel();
            var roles = new List<IdentityRole>();

            if (tc.Equals("") || tc.Equals("empty"))
            {
                roles = context.Roles.Where(x => !x.Name.Contains("_")).OrderBy(r => r.Name).ToList();//только общие роли admin и manager
            }
            else
            {
                tc = string.Format("_{0}", tc);
                roles = context.Roles.Where(x => x.Name.Contains(tc)).OrderBy(r => r.Name).ToList();//роли admin_tc, etc.
            }
            
            foreach (var user in context.Users)
            {
                var userViewModel = new SelectionUserEditorViewModel()
                {
                    Id = user.Id,
                    UserName = user.UserName
                };
                userViewModel.Roles = roles.Select(
                    role => new SelectionRoleEditorViewModel()
                    {
                        Name = role.Name,
                        Selected = userManager.IsInRole(user.Id, role.Name)
                    }).ToList();

                model.Users.Add(userViewModel);
            }
            ViewBag.Roles = roles;
            return View(model);
        }


        [HttpPost]
        public async Task<ActionResult> SubmitSelected(SelectionUsersRolesViewModel model)
        {
            var account = new AccountController();
            var roles = context.Roles.OrderBy(r => r.Name).ToList();

            foreach (var user in model.Users)
            {
                foreach (var role in user.Roles)
                {
                    if (needRemoveRole(account.UserManager, user, role))
                    {
                        await account.UserManager.RemoveFromRoleAsync(user.Id, role.Name);
                    }
                    else if (needAddRole(account.UserManager, user, role))
                    {
                        await account.UserManager.AddToRoleAsync(user.Id, role.Name);
                    }
                }
            }
            return RedirectToAction("Index");
        }


        private bool needRemoveRole(UserManager<ApplicationUser> userManager, SelectionUserEditorViewModel user, SelectionRoleEditorViewModel role)
        {
            return userManager.IsInRole(user.Id, role.Name) && !role.Selected;
        }
        private bool needAddRole(UserManager<ApplicationUser> userManager, SelectionUserEditorViewModel user, SelectionRoleEditorViewModel role)
        {
            return !userManager.IsInRole(user.Id, role.Name) && role.Selected;
        }
    }
}

TrainingCentersCRM/TrainingCentersCRM/Views/UserRoles/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using TrainingCentersCRM.Infrastructure
@model TrainingCentersCRM.Models.SelectionUsersRolesViewModel
<div class="row">
    <div class="small-12">
        <h2>Назначение ролей</h2>
        <p style="color: #999">
            На сайте установлено разграничение доступа пользователей по ролям.
            Для назначения роли админа и менеджера главного сайта выберите пункт "Роли главного сайта".
            Для назначения пользователям ролей определенного учебного центра
            выберите его название в выпадающем списке.
        </p>
    </div>
</div>
<div class="row">
    <div class="small-9 columns">
        <label for="tc-select" class="control-label col-md-4">Выберите учебный центр:</label>
        <select id="tc-select" class="form-control" onchange="window.location.href=this.value">
            <option value="@Url.Action("Index", "UserRoles", new { tc = "empty" })">Главные роли</option>
            @foreach (var tc in TCHelper.GetAllTc())
            {
                if (!tc.Url.Equals("empty"))
                {
                    <option value="@Url.Action("Index", "UserRoles", new { tc = tc.Url })">
                        @tc.Organization
                    </option>
                }
            }
        </select>
        <script type="text/javascript">
            var element = document.getElementById('tc-select');
            element.value = "@Request.Url.PathAndQuery";
        </script>
    </div>

    <div class="small-3 columns">
        <a href="@Url.Action("Index", "UserRoles", new { tc = "empty" })" style="float:right; margin-top:7px;">Роли главного сайта</a>
    </div>
</div>



<div class="row">
    <div class="small-12 columns">
        @using (Html.BeginForm("SubmitSelected", "UserRoles", FormMethod.Post, new { @class = "", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <table class="table table-striped">
                <tr>
                    <th>
                        Логин
                    </th>
                    <th></th>
                    @foreach (var role in ViewBag.Roles)
                    {
                        <th class="text-center">
                            @role.Name
                        </th>
                        <th></th>
                    }
                </tr>
                @Html.EditorFor(model => model.Users)
            </table>
            <input type="submit" name="operation" id="submit" class="btn btn-primary" value="Подтвердить" />
        }
    </div>
</div>

TrainingCentersCRM/TrainingCentersCRM/Views/UserRoles/Manage.cshtml
@{
    ViewBag.Title = "Manage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Manage User Roles</h2>
@Html.ActionLink("Create New Role", "Create") | @Html.ActionLink("Manage User Role", "Manage")
<hr />

<h2>Role Add to User</h2>

@using (Html.BeginForm("RoleAddToUser", "UserRoles"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @Html.TextBox("UserName")
        Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...")

    </p>

    <input type="submit" value="Save" />
}
<hr />
<h3>Get Roles for a User</h3>
@using (Html.BeginForm("GetRoles", "UserRoles"))
{
    @Html.AntiForgeryToken()
    <p>
        Username : @Html.TextBox("UserName")
        <input type="submit" value="Get Roles for this User" />
    </p>
}

@if (ViewBag.RolesForThisUser != null)
{
    <div style="background-color:yellow;">
        <h3>Roles for this user </h3>
        <ol>
            @foreach (string s in ViewBag.RolesForThisUser)
            {
                <li>@s</li>
            }
        </ol>
    </div>
}

<hr />
<h3>Delete A User from a Role</h3>

@using (Html.BeginForm("DeleteRoleForUser", "UserRoles"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <p>
        Username : @Html.TextBox("UserName")
        Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...")

    </p>

    <input type="submit" value="Delete this user from Role" />
}